### ISSUE TITLE
Getting illegal target position value sometimes

### ISSUE THREAD

**Issue by bostrt** [bostrt/homebridge-bali-blinds#8]
```
[11/12/2023, 2:36:41 PM] [homebridge-bali-blinds] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[11/12/2023, 2:36:41 PM] [homebridge-bali-blinds] Error: 
    at TargetPosition.Characteristic.characteristicWarning (/home/rbost/code/homebridge-bali-blinds/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at TargetPosition.Characteristic.validateUserInput (/home/rbost/code/homebridge-bali-blinds/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at TargetPosition.<anonymous> (/home/rbost/code/homebridge-bali-blinds/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/home/rbost/code/homebridge-bali-blinds/node_modules/tslib/tslib.js:195:27)
    at Object.next (/home/rbost/code/homebridge-bali-blinds/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/home/rbost/code/homebridge-bali-blinds/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by bostrt** [comment]
This issue is resolved in v0.0.5-beta.4 in this commit: https://github.com/bostrt/homebridge-bali-blinds/commit/070a4d29fe7aebc9942ffedd21389dfbd9a57e64#diff-e3e5a8bcb65529d3b9988acc9d4c55b85fbc6448682cdb51e39409790dda4cdaR15-R16
